version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

#Automatizacion de infraestructura digital II
#Prof. FROYLAN ALONSO PEREZ ALANIS
# GRAU MORENO MANUEL  - 220550